---
apiVersion: v1
kind: Service
metadata:
  name: drupal-mysql-service
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
  selector:
    app: drupal
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: drupal-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: seto_password
            - name: MYSQL_DATABASE
              value: drupal_databases
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          volumeMounts:
            - name: vol-drupal
              mountPath: /var/lib/mysql
              subPath: dbdata
      volumes:
        - name: vol-drupal
          persistentVolumeClaim:
            claimName: drupal-seto-mysql
